name: Release
on:
  release:
    types:
      - published
permissions:
  contents: write
  repository-projects: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install depencies
        run: ./scripts/install_deps.sh
      - name: Build x64
        run: ./scripts/build.sh --arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format zip
      - name: Build arm64
        run: ./scripts/build.sh --arch arm64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format zip
